import type { ModelDef, Provider, ProviderRaw } from "./types";
import { computeL1, computeL2, computeL3, tier } from "./scoring";

export const MODELS: ModelDef[] = [
  {
    id: "openai/gpt-5.5",
    display: "GPT-5.5",
    owner: "OpenAI",
    officialIn: 1.25,
    officialOut: 10.0,
    ctx: 400000,
    caps: { stream: true, tool: true, json: true, zdr: true },
  },
  {
    id: "anthropic/claude-4.6-sonnet",
    display: "Claude 4.6 Sonnet",
    owner: "Anthropic",
    officialIn: 3.0,
    officialOut: 15.0,
    ctx: 200000,
    caps: { stream: true, tool: true, json: true, zdr: true },
  },
  {
    id: "google/gemini-3.1-pro",
    display: "Gemini 3.1 Pro",
    owner: "Google",
    officialIn: 1.25,
    officialOut: 10.0,
    ctx: 2000000,
    caps: { stream: true, tool: true, json: true, zdr: false },
  },
  {
    id: "deepseek/deepseek-v3.2",
    display: "DeepSeek V3.2",
    owner: "DeepSeek",
    officialIn: 0.27,
    officialOut: 1.10,
    ctx: 128000,
    caps: { stream: true, tool: true, json: true, zdr: false },
  },
  {
    id: "meta/llama-4-maverick",
    display: "Llama 4 Maverick",
    owner: "Meta",
    officialIn: 0.27,
    officialOut: 0.85,
    ctx: 1000000,
    caps: { stream: true, tool: true, json: true, zdr: false },
  },
  {
    id: "mistral/mistral-large-2.1",
    display: "Mistral Large 2.1",
    owner: "Mistral",
    officialIn: 2.0,
    officialOut: 6.0,
    ctx: 128000,
    caps: { stream: true, tool: true, json: true, zdr: false },
  },
];

const PROVIDERS_RAW: ProviderRaw[] = [
  {
    slug: "portkey",
    name: "Portkey",
    type: "gateway",
    domain: "portkey.ai",
    website: "https://portkey.ai",
    crypto: false,
    walletPay: false,
    region: "Global",
    costIn: 5.55,
    costOut: 16.65,
    costDelta: 11,
    ref: 10.0,
    latency: 1.5,
    p95: 3.1,
    ttft: 0.35,
    success: 0.992,
    samples: 2418,
    overall: 87,
    volume7d: 28650,
    scores: {
      L1: { modelAuth: 94, billingTrans: 92, cacheFraud: 88 },
      L2: { latency: 78, throughput: 82, longContext: 80 },
      L3: { listPricing: 78, relativeToOfficial: 78, hiddenCost: 88 },
    },
    spark: [11.4, 11.6, 11.2, 11.0, 10.9, 11.1, 11.0, 11.1, 10.8, 11.1, 11.3, 11.1],
    trustParts: { modelConsistency: 92, providerMatch: 95, fallbackTransparency: 88, pricingIntegrity: 91, safety: 90 },
    incidents: [
      { time: "4h ago", issue: "Brief 5xx surge in EU during deploy", sev: "low" },
      { time: "2d ago", issue: "Latency spike (p95 → 4.8s) for 7 min", sev: "low" },
    ],
    desc: "Production-grade AI gateway with first-class observability, guardrails and routing controls.",
  },
  {
    slug: "openrouter",
    name: "OpenRouter",
    type: "router",
    domain: "openrouter.ai",
    website: "https://openrouter.ai",
    crypto: true,
    walletPay: true,
    region: "US/EU",
    costIn: 6.15,
    costOut: 18.45,
    costDelta: 23,
    ref: 10.0,
    latency: 1.2,
    p95: 2.7,
    ttft: 0.31,
    success: 0.985,
    samples: 5102,
    overall: 83,
    volume7d: 24180,
    scores: {
      L1: { modelAuth: 72, billingTrans: 82, cacheFraud: 72 },
      L2: { latency: 88, throughput: 82, longContext: 80 },
      L3: { listPricing: 75, relativeToOfficial: 72, hiddenCost: 92 },
    },
    spark: [12.0, 11.8, 12.1, 12.6, 12.4, 12.2, 12.3, 12.5, 12.3, 12.1, 12.3, 12.3],
    trustParts: { modelConsistency: 78, providerMatch: 85, fallbackTransparency: 72, pricingIntegrity: 89, safety: 86 },
    incidents: [
      { time: "2h ago", issue: "Suspected fallback to non-canonical model", sev: "medium" },
      { time: "12h ago", issue: "Pricing drift +6% for 40 min", sev: "medium" },
    ],
    desc: "Aggregator router across 100+ models. Supports crypto and on-chain payments.",
  },
  {
    slug: "bai",
    name: "B.ai",
    type: "router",
    domain: null,
    website: null,
    crypto: true,
    walletPay: true,
    region: "Global",
    costIn: 4.90,
    costOut: 14.70,
    costDelta: -2,
    ref: 10.0,
    latency: 1.0,
    p95: 2.5,
    ttft: 0.28,
    success: 0.961,
    samples: 1834,
    overall: 79,
    volume7d: 16920,
    scores: {
      L1: { modelAuth: 68, billingTrans: 78, cacheFraud: 65 },
      L2: { latency: 85, throughput: 78, longContext: 72 },
      L3: { listPricing: 92, relativeToOfficial: 88, hiddenCost: 82 },
    },
    spark: [10.4, 10.1, 9.9, 9.6, 9.8, 9.5, 9.8, 9.7, 9.8, 9.9, 10.0, 9.8],
    trustParts: { modelConsistency: 71, providerMatch: 76, fallbackTransparency: 64, pricingIntegrity: 84, safety: 82 },
    incidents: [
      { time: "1h ago", issue: "Output token count divergence vs. peers", sev: "medium" },
      { time: "6h ago", issue: "Higher refusal rate on safety prompts", sev: "low" },
    ],
    desc: "Cost-optimized aggregator with native crypto rails and Asia-Pacific coverage.",
  },
  {
    slug: "together",
    name: "Together AI",
    type: "inference",
    domain: "together.ai",
    website: "https://together.ai",
    crypto: false,
    walletPay: false,
    region: "US",
    costIn: 4.20,
    costOut: 12.60,
    costDelta: -16,
    ref: 10.0,
    latency: 0.9,
    p95: 2.1,
    ttft: 0.22,
    success: 0.994,
    samples: 4012,
    overall: 90,
    volume7d: 52840,
    scores: {
      L1: { modelAuth: 90, billingTrans: 92, cacheFraud: 82 },
      L2: { latency: 92, throughput: 88, longContext: 82 },
      L3: { listPricing: 92, relativeToOfficial: 95, hiddenCost: 88 },
    },
    spark: [8.6, 8.5, 8.3, 8.2, 8.4, 8.3, 8.4, 8.5, 8.4, 8.3, 8.4, 8.4],
    trustParts: { modelConsistency: 90, providerMatch: 91, fallbackTransparency: 81, pricingIntegrity: 93, safety: 88 },
    incidents: [{ time: "1d ago", issue: "Cold-start latency on Llama variants", sev: "low" }],
    desc: "Direct inference provider for open-weight models. High throughput, low latency.",
  },
  {
    slug: "fireworks",
    name: "Fireworks AI",
    type: "inference",
    domain: "fireworks.ai",
    website: "https://fireworks.ai",
    crypto: false,
    walletPay: false,
    region: "US",
    costIn: 4.45,
    costOut: 13.35,
    costDelta: -11,
    ref: 10.0,
    latency: 0.8,
    p95: 1.9,
    ttft: 0.19,
    success: 0.991,
    samples: 3502,
    overall: 89,
    volume7d: 39200,
    scores: {
      L1: { modelAuth: 88, billingTrans: 89, cacheFraud: 85 },
      L2: { latency: 95, throughput: 92, longContext: 85 },
      L3: { listPricing: 88, relativeToOfficial: 90, hiddenCost: 85 },
    },
    spark: [9.0, 8.8, 8.7, 9.0, 8.9, 8.9, 8.8, 8.9, 9.0, 8.9, 8.8, 8.9],
    trustParts: { modelConsistency: 88, providerMatch: 89, fallbackTransparency: 79, pricingIntegrity: 90, safety: 86 },
    incidents: [],
    desc: "High-speed inference with FireAttention runtime for OSS models.",
  },
  {
    slug: "anyscale",
    name: "Anyscale",
    type: "inference",
    domain: "anyscale.com",
    website: "https://www.anyscale.com",
    crypto: false,
    walletPay: false,
    region: "US/EU",
    costIn: 5.25,
    costOut: 15.75,
    costDelta: 5,
    ref: 10.0,
    latency: 1.4,
    p95: 3.4,
    ttft: 0.42,
    success: 0.978,
    samples: 1422,
    overall: 78,
    volume7d: 7840,
    scores: {
      L1: { modelAuth: 82, billingTrans: 82, cacheFraud: 72 },
      L2: { latency: 72, throughput: 78, longContext: 78 },
      L3: { listPricing: 80, relativeToOfficial: 75, hiddenCost: 80 },
    },
    spark: [10.3, 10.4, 10.6, 10.5, 10.7, 10.4, 10.5, 10.5, 10.6, 10.4, 10.5, 10.5],
    trustParts: { modelConsistency: 82, providerMatch: 83, fallbackTransparency: 74, pricingIntegrity: 85, safety: 78 },
    incidents: [{ time: "3h ago", issue: "p95 latency drift +18%", sev: "low" }],
    desc: "Ray-based scalable inference across Llama, Mixtral and DeepSeek families.",
  },
  {
    slug: "replicate",
    name: "Replicate",
    type: "inference",
    domain: "replicate.com",
    website: "https://replicate.com",
    crypto: false,
    walletPay: false,
    region: "Global",
    costIn: 6.80,
    costOut: 20.40,
    costDelta: 36,
    ref: 10.0,
    latency: 1.8,
    p95: 4.2,
    ttft: 0.55,
    success: 0.969,
    samples: 928,
    overall: 71,
    volume7d: 4520,
    scores: {
      L1: { modelAuth: 78, billingTrans: 80, cacheFraud: 70 },
      L2: { latency: 62, throughput: 72, longContext: 78 },
      L3: { listPricing: 58, relativeToOfficial: 50, hiddenCost: 78 },
    },
    spark: [13.2, 13.4, 13.6, 13.8, 13.5, 13.6, 13.7, 13.6, 13.4, 13.6, 13.7, 13.6],
    trustParts: { modelConsistency: 79, providerMatch: 80, fallbackTransparency: 70, pricingIntegrity: 81, safety: 75 },
    incidents: [{ time: "8h ago", issue: "Cold-start spikes on shared GPUs", sev: "medium" }],
    desc: "Marketplace of model variants. Convenience-first, less optimized for cost.",
  },
  {
    slug: "litellm",
    name: "LiteLLM",
    type: "self_host",
    domain: null,
    website: "https://github.com/BerriAI/litellm",
    crypto: false,
    walletPay: false,
    region: "Self-hosted",
    costIn: 5.00,
    costOut: 15.00,
    costDelta: 0,
    ref: 10.0,
    latency: 1.1,
    p95: 2.4,
    ttft: 0.30,
    success: 0.988,
    samples: 612,
    overall: 82,
    volume7d: 3260,
    scores: {
      L1: { modelAuth: 88, billingTrans: 92, cacheFraud: 82 },
      L2: { latency: 80, throughput: 75, longContext: 78 },
      L3: { listPricing: 92, relativeToOfficial: 88, hiddenCost: 90 },
    },
    spark: [10.0, 10.1, 9.9, 10.0, 10.0, 9.9, 10.1, 10.0, 10.0, 10.1, 9.9, 10.0],
    trustParts: { modelConsistency: 85, providerMatch: 88, fallbackTransparency: 86, pricingIntegrity: 95, safety: 80 },
    incidents: [],
    desc: "Open-source proxy. Pricing reflects upstream cost only — true pass-through.",
  },
];

export const PROVIDERS: Provider[] = PROVIDERS_RAW.map((p) => {
  const cost = Math.round(((p.costIn + p.costOut) / 2) * 100) / 100;
  const L1 = computeL1(p.scores);
  const L2 = computeL2(p.scores);
  const L3 = computeL3(p.scores);
  const overall = Math.round(L1 * 0.4 + L3 * 0.4 + L2 * 0.2);
  return { ...p, cost, trust: L1, L1, L2, L3, overall, tier: tier(overall) };
});

// Aggregate stats — derived once from PROVIDERS, used by Hero / Header
export const HERO_STATS = (() => {
  const totalSamples = PROVIDERS.reduce((s, p) => s + p.samples, 0);
  const costs = PROVIDERS.map((p) => p.cost);
  const minC = Math.min(...costs);
  const maxC = Math.max(...costs);
  const variance = Math.round(((maxC - minC) / minC) * 100);
  const incidents = PROVIDERS.flatMap((p) => p.incidents);
  const paidShare = 0.32;
  const avgRunCostUsd = 0.42;
  const paidRuns24h = Math.round(totalSamples * paidShare);
  const paymentVolume = Math.round(paidRuns24h * avgRunCostUsd * 100) / 100;
  return {
    activeRouters: PROVIDERS.length,
    cryptoCount: PROVIDERS.filter((p) => p.crypto).length,
    variance,
    driftTotal: incidents.length,
    driftMedium: incidents.filter((i) => i.sev === "medium").length,
    totalSamples,
    paidRuns24h,
    paymentVolume,
  };
})();

export const TOTAL_SAMPLES = HERO_STATS.totalSamples;
